CREATE TABLE IF NOT EXISTS House(
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name NCHAR(50) NOT NULL,
  Building NCHAR(50) NOT NULL,
  Region NCHAR(50) NOT NULL,
  District NCHAR(50) NOT NULL,
  TotalPrice INT NOT NULL,
  UnitPrice REAL NOT NULL,
  Time INT NOT NULL,
  FloorCount INT NOT NULL,
  Area REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS Building(
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name NCHAR(50) NOT NULL,
  Region NCHAR(50) NOT NULL,
  District NCHAR(50) NOT NULL,
  Decription NCHAR(500) NOT NULL,
  BuildingCount INT NOT NULL,
  HouseCount INT NOT NULL,
  Time INT NOT NULL,
  Alias NCHAR(200) NOT NULL
);